spring.datasource.url=jdbc:mysql://${SPRING_DATASOURCE_URL}.mysql.database.azure.com:3306/applicationanalyzerbackend-database?useSSL=true&requireSSL=false
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}@${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
